sensor_kit_base_link:
  cam_fc/camera_link:
    x: 2.193
    y: 0.0
    z: 1.705
    roll: 0.0
    pitch: 0.174533
    yaw: 0.0
  cam_fr/camera_link:
    x: 2.175
    y: -0.585
    z: 1.705
    roll: 0.0
    pitch: 0.174533
    yaw: -1.22173
  cam_fl/camera_link:
    x: 2.175
    y: 0.585
    z: 1.705
    roll: 0.0
    pitch: 0.174533
    yaw: 1.22173
  cam_rc/camera_link:
    x: -0.34
    y: -0.001
    z: 1.75
    roll: 0.0
    pitch: 0.174533
    yaw: 3.14159
  cam_rr/camera_link:
    x: -0.26
    y: -0.582
    z: 1.75
    roll: 0.0
    pitch: 0.174533
    yaw: -1.5708
  cam_rl/camera_link:
    x: -0.26
    y: 0.582
    z: 1.75
    roll: 0.0
    pitch: 0.174533
    yaw: 1.5708
  cam_fcr/camera_link:
    x: 2.163
    y: -0.385
    z: 1.705
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  cam_fcl/camera_link:
    x: 2.163
    y: 0.385
    z: 1.705
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lidar_ouster_left:
    x: 2.312053
    y: 0.581505
    z: 1.610277
    roll: -0.3461248
    pitch: 0.0165291
    yaw: -0.0162606
  lidar_ouster_right:
    x: 2.311906
    y: -0.664888
    z: 1.612698
    roll: 0.3551248
    pitch: 0.0165291
    yaw: 0.0061281
  lidar_innovusion_front:
    x: 2.259
    y: 0.0
    z: 1.600
    roll: 3.14159265
    pitch: -1.369065
    yaw: 0.0
  lidar_innovusion_rear:
    x: -0.3987347
    y: 0.002735673
    z: 1.760425312
    roll: 0.0000291
    pitch: -1.7552732
    yaw: 0.0
  gnss_link: # TODO: adjust name and position
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0